config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  
  root 'pages#index'
  get 'pages/help'
  
  resources :users
  resources :topics
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  get 'favorites/index'
  post '/favorites' => "favorites#create"
  delete '/favorites' => "favorites#destroy"
  
  get 'comments/new' 
  post '/comments' => "comments#create"
  delete '/comments' => "comments#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :sentence, presence: true
  validates :user_id, presence: true
  validates :topic_id, presence: true
  
  belongs_to :user
  belongs_to :topic
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  validates_uniqueness_of :topic_id, scope: :user_id
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true
  
  belongs_to :user
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  has_many :comments
  
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  # 正規表現
  EMAIL_REGULAR = /\A([^@\s]+)@[a-zA-Z0-9]+\.[a-zA-Z0-9-\.]+\z/
  PASS_REGULAR = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)[a-zA-Z\d]{8,32}+\z/
  
  # バリデーション
  validates :name, presence: true, length: {maximum: 15}
  validates :email, presence: true, uniqueness: true, format: { with: EMAIL_REGULAR}
  validates :password, presence: true, format: { with: PASS_REGULAR}
  
  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
  has_many :comment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # webサイトの脆弱性をなんとかする
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger
  
  helper_method :current_user, :logged_in?
  # ↑でcurrent_userとlogged_in?がviewで使える?
  def current_user
  @current_user ||= User.find_by(id:session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    if params[:topic_id]
      @topic = Topic.find_by(id: params[:topic_id]) 
      @comment = Comment.new
      @comments = Comment.where(topic_id: params[:topic_id])
    else
      @topic = Topic.find_by(id: params[:comment][:topic_id]) 
      @comment = Comment.new
      @comments = Comment.where(topic_id: params[:comment][:topic_id])
    end
  end
  
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      # flashはなくてもいいかも
      redirect_to comments_new_path(comment: comment_params), success: "コメントを送信しました"
    else
      @topic = Topic.find_by(id: params[:comment][:topic_id])
      @comments = Comment.where(topic_id: params[:comment][:topic_id])
      flash.now[:danger] = "コメントを送れません"
      render :new
    end
  end
    
  def destroy
    comment =Comment.find_by(id: params[:comment_id])
    comment.destroy
    redirect_to topics_path, info: "コメントを削除しました"
  end
  
  def comment_params
    params.require(:comment).permit(:sentence, :topic_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_topics = current_user.favorite_topics
  end
  
  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]
    
    if favorite.save
      redirect_to topics_path, success: 'お気に入りに登録しました'
    else
      redirect_to topics_path, danger: 'お気に入りに登録に失敗しまして'
    end
  end
  
  def destroy
    favorite = Favorite.find_by(topic_id: params[:topic_id], user_id: current_user.id)
    favorite.destroy
    redirect_to topics_path
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path, success: 'ログイン成功'
    else
      flash.now[:danger] = "ログイン失敗"
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_url, info: "ログアウトしました"
  end
  
  private
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def session_params
   params.require(:session).permit(:email, :password)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all.includes(:favorite_users)
  end
  
  def new
    @topic = Topic.new
  end
  
  def create
    @topic = current_user.topics.new(topic_params)
    # binding.pry
    if @topic.save
      redirect_to topics_path, success: "投稿完了"
    else
      flash.now[:danger] = "投稿失敗"
      render :new
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:image, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: "登録完了"
    else
      flash.now[:danger] = "登録失敗"
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confrimation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="topic-index-single">
          <h2 class="topic-author">
            <%= @topic.user.name %>
          </h2>
          <%= image_tag @topic.image.url %>
          <% if !@topic.favorite_users.include?(current_user) %>
            <%= link_to favorites_path(topic_id: @topic.id), method: :post do %>
              <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
              <!--topic(Topicのインスタンスと紐付いているfavorite_idの数か？)-->
              <%= @topic.favorites.count %>
            <% end %>
          <% else %>
            <%= link_to favorites_path(topic_id: @topic.id), method: :delete do %>
              <%= image_tag "icons/heart-black.png", class: 'topic-index-icon heart-red' %>
              <%= @topic.favorites.count %>
            <% end %>
          <% end %>
          <%= link_to comments_path(topic_id: @topic.id) do %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
          <% end %>
          <p class="topic-text">
            <%= @topic.description %>
          </p>
          <p class="comment-title">コメント</p>
          <% @comments.each do |comment| %>
            <div>
              <%= comment.user.name %>
            </div>
            <div class="comment-sentence">
              <%= comment.sentence %>
            </div>
            <% if comment.user_id = current_user.id %>
              <%= link_to "削除", comments_path(comment_id: comment.id), class: 'btn', method: :delete %>
            <% end %>
          <% end %>
          <%= form_for @comment do |f| %>
          <p>コメント</p>
            <div>
              <%= f.text_area :sentence, class: "text-area" %>
            </div>
            <%= f.hidden_field :topic_id, :value => @topic.id %>
            <%= f.submit 'コメントする', class: 'btn btn-black btn-block' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert">
        <%= value %>
      </div>
    <% end %>
    
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to root_path do %>
        <span><%= image_tag "icons/logo.png", class: "navbar-brand", title: "トップ" %></span>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%= link_to topics_path do %>
                <p>投稿一覧</p>
              <% end %>
            </li>
            <li>
              <%= link_to favorites_index_path do %>
                <%= image_tag "icons/heart.png", title: "いいね一覧" %>
              <% end %>
            </li>
            <li>
              <%= link_to new_topic_path do %>
                <%= image_tag "icons/camera.png", title: "新規投稿" %>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete, title: "ログアウト" do %>
                <%= image_tag "icons/logout.png" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_path, title: "新規登録" do %>
                <%= image_tag "icons/register.png" %>
              <% end %>
            </li>
            <li>
            <%= link_to login_path do %>
              <%= image_tag "icons/login.png", title: "ログイン" %>
            <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
    
    <!--jQueryを使っている-->
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>
  </body>
</html>

app/views/pages/help.html.erb
<h1>ヘルプページです</h1>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Make you happy</h1>
    <h2 class="text-white">Pictgram is a service that you can post photos.</h2>
    <!--以下はそのうち削除しましょう-->
    <h2>課題用テスト</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to 'sign up', new_user_path, class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'Log in', login_path, class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <% if !topic.favorite_users.include?(current_user) %>
              <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
                <!--topic(Topicのインスタンスと紐付いているfavorite_idの数か？)-->
              <% end %>
            <% else %>
              <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                <%= image_tag "icons/heart.png", class: 'topic-index-icon heart-red' %>
              <% end %>
            <% end %>
            <%= topic.favorites.count %>
            <%= link_to comments_new_path(topic_id: topic.id) do %>
              <%= image_tag 'icons/comment.png', class: 'topic-index-icon ' %>
              <%= topic.comments.count %>
            <% end %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image %>
          </div>
          
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
          <% if logged_in? %>
            <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
          <% else %>
            <%= link_to 'ログインはこちら', login_path, class: 'btn btn-black btn-block' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign up</h1>
        <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :name, class: 'text-white' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email, class: 'text-white' %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label:password, class: 'text-white' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label:password_confirmation, class: 'text-white' %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <%= f.submit "新規登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
      </div>
    </div>
  </div>
</div>